apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: httpd
          name: httpd
          command: ["bin/bash", "-C"] # Override the default command
          args: ["sleep 3; exit 1"]   # Sleep for 30 seconds then exit with an error

  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1

